language: node_js

node_js:
  - node

sudo: required
addons:
  chrome: stable --no-sandbox

before_script:
  - cd webapp

script:
  - npm install -g --silent @angular/cli
  - npm install -g @angular-devkit/build-angular
  - npm link
  - ng test
  - ng build --prod

notifications:
  - email:
    on_failure: change
    on_success: change
